# Generated by Django 5.1.7 on 2025-05-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customer_country_customer_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
