# Generated by Django 5.1.7 on 2025-05-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
    ]
