# Generated by Django 5.1.7 on 2025-05-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
