# Generated by Django 5.1.7 on 2025-05-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_order_customer_order_product_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
