# Generated by Django 5.1.7 on 2025-05-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('CARD', 'Card'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer')], default='COD', max_length=20),
        ),
    ]
