# Generated by Django 5.1.7 on 2025-05-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_order_is_paid_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='order_date',
        ),
    ]
